### ISSUE TITLE
TBD: Creating a URL Validator

### ISSUE THREAD

**Issue by shentschel** [viion/lodestone-php#17]
After a brief discussion in https://github.com/viion/lodestone-php/pull/16 we should decide if there is the need for implementing a url validation.

The validation would contain a check :

- [x] if the url is from `finalfantasyxiv`
- [ ] for forum posts
- [ ] for dev posts

The question to discuss is: Will there be enough wrong urls to be worth implementing a url validation which can be changed every time.

Should we decide to implement this validation we can reference this issue to keep track of the discussion :)

**Comment by viion** [comment]
It is true that it is unlikely SE will provide invalid URLs, my assumption is mostly based on if the parsing of a url fails, here is an example for what I am wanting to look out for:

**Avatar HTML**

```html
<div class="frame__chara__face">
    <img src="http://img2.finalfantasyxiv.com/f/73cbde3df508fa147006c64859727aae_5047bc596a4bab2dc7f7c120bb22dec5fc0_96x96.jpg?1495113336" width="40" height="40" alt="">
</div>
```

Lets say they decide to use lazy-loading or something and no longer use `src`

```html
<div class="frame__chara__face">
    <img data-src="http://img2.finalfantasyxiv.com/f/73cbde3df508fa147006c64859727aae_5047bc596a4bab2dc7f7c120bb22dec5fc0_96x96.jpg?1495113336" width="40" height="40" alt="">
</div>
```

The parser would now return a blank entry for `avatar`, a simple `isEmpty/isString` would be enough.

So, what if they change urls to be relative? (unlikely since they're served on a CDN, but *maybe*)

```html
<div class="frame__chara__face">
    <img data-src="/f/73cbde3df508fa147006c64859727aae_5047bc596a4bab2dc7f7c120bb22dec5fc0_96x96.jpg?1495113336" width="40" height="40" alt="">
</div>
```

The avatar would return but it would be useless. In some areas of the parser (eg parsing urls) they use relative links, makes sense and we have to append on the lodestone url to ensure full links. Want to try test if this ever changes.

**Relative links**

```html
<a href="/lodestone/character/730968/" class="frame__chara__link">
...
</a>
```

Most urls are like this and the parser appends on the main domain. However, SE might decide to do that themselves (unsure they would but *maybe*)

```html
<a href="http://eu.finalfantasyxiv.com/lodestone/character/730968/" class="frame__chara__link">
...
</a>
```

This parsed would end up as:

- `http://eu.finalfantasyxiv.com/http://eu.finalfantasyxiv.com/lodestone/character/730968/`

Which contains a duplication.

Just food for thought, it might be something we just handle as and when it arrives.

**Comment by shentschel** [comment]
Hmm for the case with the relative URL we could provide something like `isRelativeUrl()`

which would implement a regex check like `^https?`. This would check if an URL starts with either http or https. So we wouldn't need to redesign it every time square wants to change some url stuff.

**Comment by Simbiat** [comment]
this could simplify updates of the parser after LS updates, so I vote this in :D

**Comment by shentschel** [comment]
Is there something we need to do for this issue? Currently we have a check for relative urls. If that is enough we can close this issue :)

**Comment by viion** [comment]
Yup, think it's all done!
