### ISSUE TITLE
toArray strips NULLs

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#51]
Seems like Characters' toArray strips all NULLs and 0s when preparing an array. Can be easily recreated on http://eu.finalfantasyxiv.com/lodestone/character/17257994/ - you lose grandcompany and some levels.
I thought it was because of
```php
if (isset($result['var'])) {
```
condition (would explain NULLs at least), but seems like it's not - commenting did not do anything

**Comment by viion** [comment]
Didn't you provide a fix for this? 

Working now anyway.

**Comment by Simbiat** [comment]
I added isset, but that's not what is causing the problem. at least judging by my debug.

**Comment by viion** [comment]
Is this still happening for you? I checked the character you posted and it returns empty data where expected

**Comment by Simbiat** [comment]
Guess it was fixed by something else, dunno. But it does not return "Scholar" now... I mean like it's not returned at all. Seems it's true even for those, who have scholars

**Comment by viion** [comment]
I don't know how SE handle it, I assume if you last equipped summoner it would show that instead of Arcanist, if you last equipped Scholar it would show that. I can check tomorrow but Arcanist ID should exist and the name will be w/e lodestone shows.

**Comment by Simbiat** [comment]
Erhm... I guess I was not clear enough... I was not talking about Active Class, but about classes in general. Like levels. And they are both showed now. Even for Ragnalock (the guy I posted above).

**Comment by viion** [comment]
This is what lodestone does apparently: http://eu.finalfantasyxiv.com/lodestone/character/17257994/

Treats "Scholar" as it's own class. The code is just ripping from that list, i don't really have control over it, it's not something I've programmed. It's going through the html and grabbing what is there, whatever SE do, is how the output will be.

I wonder why they've done it like that, maybe to show more healers than just 2-3.

The code should detect the ID for this though and just show one because the array index is the class/job id, unless i've made a spelling mistake in the convert array.

**Comment by Simbiat** [comment]
I am telling you, before today's updates I was getting both Scholar and Summoner. Granted, in my code I can make them equal to each other, but I'd prefer to have... consistency.

**Comment by viion** [comment]
Yes, **before** because SE list BOTH on the page, click any lodestone profile, click on classes and you will see both.

However, in the API I concat these, eg:

```
    [26] => Lodestone\Entities\Character\ClassJob Object
        (
            [id:protected] => 26
            [name:protected] => Summoner
            [level:protected] => 50
            [expLevel:protected] => 0
            [expLevelTogo:protected] => 864000
            [expLevelMax:protected] => 864000
            [expTotal:protected] => 7734000
            [expTotalMax:protected] => 100013800
            [expTotalTogo:protected] => 92279800
        )
```

Right now it will show Summoner (or Arcanist if summoner has not been unlocked) because it's the last one out of the 2 jobs available. I don't know what I am supposed to do about this? 

Show Scholar? Show Summoner or show neither and list Arcanist, which would be inconsistent to other roles display.

The array stores data against the key, I do not want to list 2 jobs in the array when you don't technically have 2 jobs.

Or we can strip "jobs" and reduce everything down to Classes.

**Comment by Simbiat** [comment]
They are technically 2 jobs, though. 1 class, but 2 jobs. From what I see, SE turned Arcanist to Summoner (both DPS) and Scholar is added like, say, Astrologian. Only difference is shared exp. In my understanding, both jobs need to be shown, same as done on Lodestone.
IMHO, it's appropriate to stick to jobs, since classes are now, essentially, a legacy, which can't be removed due to need to rewrite quests, not only technically, but in terms of lore, too.

**Comment by viion** [comment]
The problem I have is they use the same IDs so they cannot be tracked individually and since they share same experience t gives a false impression that you have 1 extra classes to level.

These are meant to be levelling roles

**Comment by viion** [comment]
I am looking at keeping Scholar and Summoner in the array. The problem becomes how you store that, eg:

1) Store by CLASS ID means Summoner OVERWRITES Scholar
2) Store by JOB ID means you can have both

However for (2) there are problems with "Active Class" because your weapon would be "Archer's Arm" not "Bard's Arm", so it tries to find the class/job entry for "Archer" and fails, because it's saved by Job ID not Class ID.

Which would mean more hard coding to convert these arms to job entries...

**Comment by viion** [comment]
Done a commit for this: https://github.com/viion/lodestone-php/commit/1b652c7053137cc8dee692996c236fb3a617f6da

`classjob` array entries now contain:

- `classId`
- `jobId`

They match as expected. If you have not unlocked the job, then your `jobId` will be the same as your `classId`.

If you have equipped a Job (eg Bard), it will correctly fetch that based on if you have the JobStone equipped or not.

```
[activeClassJob:protected] => Lodestone\Entities\Character\ClassJob Object
(
    [jobId:protected] => 23
    [classId:protected] => 5
    [name:protected] => Bard
    [level:protected] => 58
    [expLevel:protected] => 463720
    [expLevelTogo:protected] => 2963480
    [expLevelMax:protected] => 3427200
    [expTotal:protected] => 22619320
    [expTotalMax:protected] => 100013800
    [expTotalTogo:protected] => 77394480
)
```

It would be good to test this. The array index of `classjob` is now deemed useless for developer use and only to be used internally for retrieval as it will either save as `jobId` or `classId` depending on if you have unlocked the job or not (in which case Lodestone represents it differently). Index is stored as Job so that Scholar and Summoner can be individually tracked.

**Comment by shentschel** [comment]
How about separately storing jobs and classes and use classes as fallback if job is not found? It is only an idea and open for discussion:)

**Comment by viion** [comment]
I don't want to store two arrays, it becomes very unwieldily then. You'd also still need references from jobs back to classes which exist now.

Ideally everything should just get put down to class which is how it was. Having "Paladin" listed imo is silly because you don't level Paladin!!!

**Comment by viion** [comment]
As the topic of this has been moved off from the original issue I am going to close it and open a new issue regarding SMN/ACN and SCH situation just incase there are any final thoughts.
