### ISSUE TITLE
Feasts number getting NULLed

### ISSUE THREAD

**Issue by Simbiat** [viion/lodestone-php#91]
New PvPTeam feature grabs "feasts" (number of Feast battles). For some reason, doing toArray on the result turns string '0' into NULL, but I do not see any kind of conversion like this in AbstractEntity. Similar thing is actually happening with "rank" and "rankicon" too, when character is a regular member. Also, "feasts" are shown as first element for the PvPTeamMembers object for some reason.

**Comment by Simbiat** [comment]
yes, this helps (and explainable by [manual](http://php.net/manual/en/language.types.boolean.php#language.types.boolean.casting)). I am not sure it will be right to do this universally, though. I do not remember any other values, that can be string '0' (not int as in your sample), but still.
Should not we be using is_set in here?

**Comment by viion** [comment]
`isset` no, as `$var = null` would pass `isset`. The initial idea for this bit of code was to make everything null that was some sort of false value. It was pre-emptive and so there wasn't an example which motivated the logic.

My idea was, if lodestone returned: `''` or `0` or `null` or `false` then these would all end up being `null`. I honestly think with our validation handling this would never really happen, if something is empty and we don't expect it to be then it usually caught by the validation handler, otherwise it is likely a true false value.

I am considering if it would be right to do universally since we have strong validation and there can be `0` allowed. 

Do you think of any place where a returned 0 might be something a developer wouldn't expect in the data?

**Comment by Simbiat** [comment]
well, I do not think I encountered anything where it could cause problems, but personally, I'd prefer NULLing in the constructors, like making it a default value, rather then arbitrary converting anything. Like with those rankicons: it makes sense for them to be NULL if we do not have an icon to be used in the first place. Everything else is handled by validator then.

**Comment by viion** [comment]
Yeah I agree, we could handle the Feast scenerio individually if it needs to have a genuine `0` value.

**Comment by Simbiat** [comment]
so, should I remove this check in AbstractEntity and update all other entities with default values of NULL?

**Comment by viion** [comment]
It isn't so much about what the default value is, it is what lodestone returns, for example:

```
<div class="something">
      <span>SomeVal</span>
</div>
```

If you parse that as `.something span` you get SomeVal.

```
<div class="something">
      <span></span>
</div>
```

If you parse that you get `''` an empty string, the `toArray` would then be:

```
{
    field => '',
}
```

The html existed on Lodestone but the data was empty and thus it just returns an empty string, this isn't the same as `null`, so it becomes inconsistent.

The solution would be to either allow 0 values and not set them null, or they become null and the developers have to deal with that.

**Comment by viion** [comment]
Closing this as the repository is going to be discontinued.
